--Script automatically executed on startup by Hibernate
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS library;
DROP TABLE IF EXISTS external_library;

CREATE TABLE author (
    id bigint NOT NULL AUTO_INCREMENT,
    name varchar(255),
    lastname varchar(20),
    PRIMARY KEY (id)
);

CREATE TABLE book (
    id bigint AUTO_INCREMENT,
    title varchar(255),
    published int,
    author_id bigint,

    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE library (
    id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
    address varchar(255)
);

CREATE TABLE external_library(
    id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
    address varchar(255)
);

INSERT INTO author(id, lastname, name) VALUES (1001, 'Mickiewicz', 'Adas');
INSERT INTO author(lastname, name) VALUES('Homer', '');
INSERT INTO author(lastname, name) VALUES('Shakespeare', 'William');
INSERT INTO author(lastname, name) VALUES('Martin', 'George R.R.');
INSERT INTO author(lastname, name) VALUES('Lucas', 'George');
INSERT INTO author(lastname, name) VALUES('Rej', 'Mikolaj');
INSERT INTO author(lastname, name) VALUES('Strugacki', 'A.A.');
INSERT INTO author(lastname, name) VALUES('Tolkien', 'John');
INSERT INTO author(lastname, name) VALUES('Slowacki', 'Juliusz');
INSERT INTO author(lastname, name) VALUES('Sun Tzu', '');
INSERT INTO author(lastname, name) VALUES('Virgil', '');
INSERT INTO author(lastname, name) VALUES('Alighieri', 'Dante');
INSERT INTO author(lastname, name) VALUES('Austen', 'Jane');
INSERT INTO author(lastname, name) VALUES('Dumas', 'Alexandre ');
INSERT INTO author(lastname, name) VALUES('Poe', 'Edgar Allan');
INSERT INTO author(lastname, name) VALUES('Dickens', 'Charles');
INSERT INTO author(lastname, name) VALUES('Melville ', 'Herman');
INSERT INTO author(lastname, name) VALUES('Orwell', 'George');
INSERT INTO author(lastname, name) VALUES('Asimov', 'Isaac');
INSERT INTO author(lastname, name) VALUES('Meyer', 'Stephanie');
INSERT INTO author(lastname, name) VALUES('Brown', 'Dan');
INSERT INTO author(lastname, name) VALUES('Rowling', 'J.K.');
INSERT INTO author(lastname, name) VALUES('Collins', 'Suzanne');
INSERT INTO author(lastname, name) VALUES('Adams', 'Douglas');
INSERT INTO author(lastname, name) VALUES('Riodan', 'Rick');
INSERT INTO author(lastname, name) VALUES('Gailman', 'Neil');
INSERT INTO author(lastname, name) VALUES('King', 'Stephen');
INSERT INTO author(lastname, name) VALUES('Coelho', 'Paulo');
INSERT INTO author(lastname, name) VALUES('Murakami', 'Haraki');
INSERT INTO author(lastname, name) VALUES('Frank', 'Anne');
INSERT INTO author(lastname, name) VALUES('Angelou', 'Maya');
INSERT INTO author(lastname, name) VALUES('Kerouac', 'Jack');
INSERT INTO author(lastname, name) VALUES('Plath', 'Sylvia');
INSERT INTO author(lastname, name) VALUES('Thompson', 'Hunter S.');
INSERT INTO author(lastname, name) VALUES('Camus', 'Albert');
INSERT INTO author(lastname, name) VALUES('Bonda', 'Katarzyna');
INSERT INTO author(lastname, name) VALUES('Tokarczuk', 'Olga');
INSERT INTO author(lastname, name) VALUES('Żulczyk', 'Jakub');
INSERT INTO author(lastname, name) VALUES('Sofokles', '');
INSERT INTO author(lastname, name) VALUES('Arystofanes', '');
INSERT INTO author(lastname, name) VALUES('Horacy', '');
INSERT INTO author(lastname, name) VALUES('Boccacio', 'Giovanni');
INSERT INTO author(lastname, name) VALUES('Chaucer', 'Geoffrey');
INSERT INTO author(lastname, name) VALUES('de Cervantes', 'Miguel');
INSERT INTO author(lastname, name) VALUES('Wolter', '');
INSERT INTO author(lastname, name) VALUES('Grimm', 'J. i W.');
INSERT INTO author(lastname, name) VALUES('Hugo', 'Wiktor');
INSERT INTO author(lastname, name) VALUES('Dostojewski', 'Fiodor');
INSERT INTO author(lastname, name) VALUES('Tołstoj', 'Lew');
INSERT INTO author(lastname, name) VALUES('Zola', 'Emil');
INSERT INTO author(lastname, name) VALUES('Luter', 'Marcin');
INSERT INTO author(lastname, name) VALUES('Blake', 'William');
INSERT INTO author(lastname, name) VALUES('Prokofiew', 'Siergiej');
INSERT INTO author(lastname, name) VALUES('Gorki', 'Maksym');
INSERT INTO author(lastname, name) VALUES('Trocki', 'Lew');
INSERT INTO author(lastname, name) VALUES('Rachmaninow', 'Siergiej');
INSERT INTO author(lastname, name) VALUES('Kuzmin', 'Michail');
INSERT INTO author(lastname, name) VALUES('Gogol', 'Mikolaj');
INSERT INTO author(lastname, name) VALUES('Majakowski', 'Wladimir');
INSERT INTO author(lastname, name) VALUES('Marszak', 'Samuel');
INSERT INTO author(lastname, name) VALUES('Pasternak', 'Borys');
INSERT INTO author(lastname, name) VALUES('Tarkowski', 'Andriej');
INSERT INTO author(lastname, name) VALUES('Jewtuszenko', 'Jewgienij');
INSERT INTO author(lastname, name) VALUES('Sołżenicyn', 'Aleksander');
INSERT INTO author(lastname, name) VALUES('Okudżawa', 'Bułat');
INSERT INTO author(lastname, name) VALUES('Kropotkin', 'Piotr');
INSERT INTO author(lastname, name) VALUES('Mussogorski', 'Modest');
INSERT INTO author(lastname, name) VALUES('Mandelstam', 'Osip');
INSERT INTO author(lastname, name) VALUES('Akunin', 'Borys');
INSERT INTO author(lastname, name) VALUES('Holderin', 'Freidrich');
INSERT INTO author(lastname, name) VALUES('Fontane', 'Theodor');
INSERT INTO author(lastname, name) VALUES('Mann', 'Thomas');
INSERT INTO author(lastname, name) VALUES('Akunin', 'Borys');
INSERT INTO author(lastname, name) VALUES('von Grimmelshausen', 'Hans Jakob Christoffel');
INSERT INTO author(lastname, name) VALUES('Rilke', 'Reiner');
INSERT INTO author(lastname, name) VALUES('Hesse', 'Herman');
INSERT INTO author(lastname, name) VALUES('Keun', 'Imgard');
INSERT INTO author(lastname, name) VALUES('Seghers', 'Anna');
INSERT INTO author(lastname, name) VALUES('Grass', 'Günter');
INSERT INTO author(lastname, name) VALUES('Wolf', 'Christa');
INSERT INTO author(lastname, name) VALUES('Böll', 'Heinrich');
INSERT INTO author(lastname, name) VALUES('Achebe', 'Chinua');
INSERT INTO author(lastname, name) VALUES('Achebe', 'Chinua');
INSERT INTO author(lastname, name) VALUES('Ngozi Adichie', 'Chimamanda');
INSERT INTO author(lastname, name) VALUES('Armah', 'Ayi Kwei');
INSERT INTO author(lastname, name) VALUES('Forna', 'Aminatta');
INSERT INTO author(lastname, name) VALUES('Nadine', 'Gordimer');
INSERT INTO author(lastname, name) VALUES('Mabanckou', 'Alain');
INSERT INTO author(lastname, name) VALUES('Okri', 'Ben');
INSERT INTO author(lastname, name) VALUES('wa Thiong’o', 'Ngugi');
INSERT INTO author(lastname, name) VALUES('Okri', 'Ben');
INSERT INTO author(lastname, name) VALUES('Soyinka', 'Wole');
INSERT INTO author(lastname, name) VALUES('Tutuola', 'Amos');
INSERT INTO author(lastname, name) VALUES('Laye', 'Camera');

INSERT INTO book(id, title, published, author_id) VALUES (2001,  'Pan Tadeusz', 1977, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Star Wars', 1997, 1005);
INSERT INTO book(title, published, author_id) VALUES ('Lord of the Rings', 1997, 1008);
INSERT INTO book(title, published, author_id) VALUES ('Song of Ice and Fire', 1997, 1004);
INSERT INTO book(title, published, author_id) VALUES ('Pan Beniowski', 1997, 1009);
INSERT INTO book(title, published, author_id) VALUES ('Hobbit', 1988, 1008);
INSERT INTO book(title, published, author_id) VALUES ('Dziady 1', 1997, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Sonety Krymske', 1988, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Kordian', 1988, 1009);
INSERT INTO book(title, published, author_id) VALUES ('Dziady 2', 1997, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Dziady 3', 1997, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Konrad Wallenrod', 1988, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Księgi narodu polskiego i pielgrzymstwa polskiego', 1988, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Liryki lozańskie', 1994, 1001);
INSERT INTO book(title, published, author_id) VALUES ('Balladyna', 1994, 1009);
INSERT INTO book(title, published, author_id) VALUES ('Fantazy', 1994, 1009);
INSERT INTO book(title, published, author_id) VALUES ('Mazepa', 2001, 1009);
INSERT INTO book(title, published, author_id) VALUES ('Ksiadz Marek', 2010, 1009);
INSERT INTO book(title, published, author_id) VALUES ('A Clash of Kings', 1999, 1004);
INSERT INTO book(title, published, author_id) VALUES ('A Storm of Swords', 2000, 1004);
INSERT INTO book(title, published, author_id) VALUES ('A Feast for Crows', 2006, 1004);
INSERT INTO book(title, published, author_id) VALUES ('A Dance with Dragons', 2011, 1004);
INSERT INTO book(title, published, author_id) VALUES ('Oddysey', 1988, 1002);
INSERT INTO book(title, published, author_id) VALUES ('Illiada', 1988, 1002);
INSERT INTO book(title, published, author_id) VALUES ('Zywot czlowieka poczciwego', 1988, 1006);

INSERT INTO library VALUES (3001, 'Wroclaw');
INSERT INTO library(address) VALUES ('Warszawa');
INSERT INTO library(address) VALUES ('Poznan');
INSERT INTO library(address) VALUES ('Pcim Dolny');
INSERT INTO library(address) VALUES ('Bielsko Biala');
INSERT INTO external_library VALUES (3006, 'Munich');
INSERT INTO external_library (address) VALUES ('Prague');
INSERT INTO external_library (address) VALUES ('Bratislava');
INSERT INTO external_library (address) VALUES ('Budapest');
INSERT INTO external_library (address) VALUES ('Ostrava');
INSERT INTO external_library (address) VALUES ('New York');
INSERT INTO external_library (address) VALUES ('Toronto');
INSERT INTO external_library (address) VALUES ('Kaliningrad');
INSERT INTO external_library (address) VALUES ('Moskwa');
INSERT INTO external_library (address) VALUES ('Jekaterynburg');
INSERT INTO external_library (address) VALUES ('Czita');
INSERT INTO external_library (address) VALUES ('Wladywostok');
INSERT INTO external_library (address) VALUES ('Perm');
INSERT INTO external_library (address) VALUES ('Smolensk');
INSERT INTO external_library (address) VALUES ('Vienna');
INSERT INTO external_library (address) VALUES ('Graz');
INSERT INTO external_library (address) VALUES ('Zurich');
INSERT INTO external_library (address) VALUES ('A Coruña');
INSERT INTO external_library (address) VALUES ('Aachen');
INSERT INTO external_library (address) VALUES ('Aarhus');
INSERT INTO external_library (address) VALUES ('Aberdeen');
INSERT INTO external_library (address) VALUES ('Abu Dhabi');
INSERT INTO external_library (address) VALUES ('Acapulco');
INSERT INTO external_library (address) VALUES ('Adelaide');
INSERT INTO external_library (address) VALUES ('Adelboden');
INSERT INTO external_library (address) VALUES ('Agadir');
INSERT INTO external_library (address) VALUES ('Agde');
INSERT INTO external_library (address) VALUES ('Agen');
INSERT INTO external_library (address) VALUES ('Agios Nikolaos');
INSERT INTO external_library (address) VALUES ('Agrigento');
INSERT INTO external_library (address) VALUES ('Agropoli');
INSERT INTO external_library (address) VALUES ('Aigues-Mortes');
INSERT INTO external_library (address) VALUES ('Aix-en-Provence');
INSERT INTO external_library (address) VALUES ('Aix-les-Bains');
INSERT INTO external_library (address) VALUES ('Ajaccio');
INSERT INTO external_library (address) VALUES ('Ajman');
INSERT INTO external_library (address) VALUES ('Akron');
INSERT INTO external_library (address) VALUES ('Al Ain');
INSERT INTO external_library (address) VALUES ('Alanya');
INSERT INTO external_library (address) VALUES ('Albany');
INSERT INTO external_library (address) VALUES ('Albufeira');
INSERT INTO external_library (address) VALUES ('Albuquerque');
INSERT INTO external_library (address) VALUES ('Alcudia');
INSERT INTO external_library (address) VALUES ('Alessandria');
INSERT INTO external_library (address) VALUES ('Ålesund');
INSERT INTO external_library (address) VALUES ('Alexandria');
INSERT INTO external_library (address) VALUES ('Algeciras');
INSERT INTO external_library (address) VALUES ('Alicante');
INSERT INTO external_library (address) VALUES ('Alkmaar');
INSERT INTO external_library (address) VALUES ('Alpe d´Huez');
INSERT INTO external_library (address) VALUES ('Alta Badia');
INSERT INTO external_library (address) VALUES ('Altea');
INSERT INTO external_library (address) VALUES ('Amalfi');
INSERT INTO external_library (address) VALUES ('Amarillo');
INSERT INTO external_library (address) VALUES ('Amersfoort');
INSERT INTO external_library (address) VALUES ('Amiens');
INSERT INTO external_library (address) VALUES ('Amsterdam');
INSERT INTO external_library (address) VALUES ('Anaheim');
INSERT INTO external_library (address) VALUES ('Anchorage');
INSERT INTO external_library (address) VALUES ('Ancona');
INSERT INTO external_library (address) VALUES ('Andalo');
INSERT INTO external_library (address) VALUES ('Andermatt');
INSERT INTO external_library (address) VALUES ('Angers');
INSERT INTO external_library (address) VALUES ('Ankara');
INSERT INTO external_library (address) VALUES ('Ann Arbor');
INSERT INTO external_library (address) VALUES ('Annapolis');
INSERT INTO external_library (address) VALUES ('Annecy');
INSERT INTO external_library (address) VALUES ('Antalya');
INSERT INTO external_library (address) VALUES ('Antibes');
INSERT INTO external_library (address) VALUES ('Antwerp');
INSERT INTO external_library (address) VALUES ('Anzio');
INSERT INTO external_library (address) VALUES ('Ao Nang');
INSERT INTO external_library (address) VALUES ('Aosta');
INSERT INTO external_library (address) VALUES ('Appleton');
INSERT INTO external_library (address) VALUES ('Aracaju');
INSERT INTO external_library (address) VALUES ('Arezzo');
INSERT INTO external_library (address) VALUES ('Argostoli');
INSERT INTO external_library (address) VALUES ('Arles');
INSERT INTO external_library (address) VALUES ('Arlington (Virginia)');
INSERT INTO external_library (address) VALUES ('Arlington (Texas)');
INSERT INTO external_library (address) VALUES ('Armagh');
INSERT INTO external_library (address) VALUES ('Arnhem');
INSERT INTO external_library (address) VALUES ('Arosa');
INSERT INTO external_library (address) VALUES ('Arrecife');
INSERT INTO external_library (address) VALUES ('Artà');
INSERT INTO external_library (address) VALUES ('Ascoli Piceno');
INSERT INTO external_library (address) VALUES ('Ashdod');
INSERT INTO external_library (address) VALUES ('Ashkelon');
INSERT INTO external_library (address) VALUES ('Aspen');
INSERT INTO external_library (address) VALUES ('Asti');
INSERT INTO external_library (address) VALUES ('Athens');
INSERT INTO external_library (address) VALUES ('Athlone');
INSERT INTO external_library (address) VALUES ('Atlanta');
INSERT INTO external_library (address) VALUES ('Atlantic City');
INSERT INTO external_library (address) VALUES ('Auckland');
INSERT INTO external_library (address) VALUES ('Augsburg');
INSERT INTO external_library (address) VALUES ('Augusta (Georgia)');
INSERT INTO external_library (address) VALUES ('Augusta (Maine)');
INSERT INTO external_library (address) VALUES ('Aurora (Colorado)');
INSERT INTO external_library (address) VALUES ('Aurora (Illinois)');
INSERT INTO external_library (address) VALUES ('Austin');
INSERT INTO external_library (address) VALUES ('Auxerre');
INSERT INTO external_library (address) VALUES ('Aveiro');
INSERT INTO external_library (address) VALUES ('Avellino');
INSERT INTO external_library (address) VALUES ('Avignon');
INSERT INTO external_library (address) VALUES ('Avoriaz');
INSERT INTO external_library (address) VALUES ('Axamer Lizum');
INSERT INTO external_library (address) VALUES ('Ayia Napa');
INSERT INTO external_library (address) VALUES ('Bad Gastein');
INSERT INTO external_library (address) VALUES ('Bad Hofgastein');
INSERT INTO external_library (address) VALUES ('Baden');
INSERT INTO external_library (address) VALUES ('Bakersfield');
INSERT INTO external_library (address) VALUES ('Baltimore');
INSERT INTO external_library (address) VALUES ('Bandar Seri Begawan');
INSERT INTO external_library (address) VALUES ('Bandol');
INSERT INTO external_library (address) VALUES ('Bangkok');
INSERT INTO external_library (address) VALUES ('Bangor');
INSERT INTO external_library (address) VALUES ('Bar');
INSERT INTO external_library (address) VALUES ('Barcelona');
INSERT INTO external_library (address) VALUES ('Bari');
INSERT INTO external_library (address) VALUES ('Barletta');
INSERT INTO external_library (address) VALUES ('Barstow');
INSERT INTO external_library (address) VALUES ('Basel');
INSERT INTO external_library (address) VALUES ('Bastia');
INSERT INTO external_library (address) VALUES ('Bath');
INSERT INTO external_library (address) VALUES ('Baton Rouge');
INSERT INTO external_library (address) VALUES ('Batumi');
INSERT INTO external_library (address) VALUES ('Bayonne');
INSERT INTO external_library (address) VALUES ('Beaulieu-sur-Mer');
INSERT INTO external_library (address) VALUES ('Beersheba');
INSERT INTO external_library (address) VALUES ('Beijing');
INSERT INTO external_library (address) VALUES ('Belfast');
INSERT INTO external_library (address) VALUES ('Belfort');
INSERT INTO external_library (address) VALUES ('Belgrade');
INSERT INTO external_library (address) VALUES ('Belluno');
INSERT INTO external_library (address) VALUES ('Belo Horizonte');
INSERT INTO external_library (address) VALUES ('Bemidji');
INSERT INTO external_library (address) VALUES ('Benalmadena');
INSERT INTO external_library (address) VALUES ('Bendigo');
INSERT INTO external_library (address) VALUES ('Benevento');
INSERT INTO external_library (address) VALUES ('Benicàssim');
INSERT INTO external_library (address) VALUES ('Benidorm');
INSERT INTO external_library (address) VALUES ('Bergamo');
INSERT INTO external_library (address) VALUES ('Bergen');
INSERT INTO external_library (address) VALUES ('Bergerac');
INSERT INTO external_library (address) VALUES ('Berkeley');
INSERT INTO external_library (address) VALUES ('Berlin');
INSERT INTO external_library (address) VALUES ('Bern');
INSERT INTO external_library (address) VALUES ('Besançon');
INSERT INTO external_library (address) VALUES ('Beverly Hills');
INSERT INTO external_library (address) VALUES ('Biarritz');
INSERT INTO external_library (address) VALUES ('Biel/Bienne');
INSERT INTO external_library (address) VALUES ('Bielefeld');
INSERT INTO external_library (address) VALUES ('Biella');
INSERT INTO external_library (address) VALUES ('Bilbao');
INSERT INTO external_library (address) VALUES ('Billings');
INSERT INTO external_library (address) VALUES ('Birmingham (UK)');
INSERT INTO external_library (address) VALUES ('Birmingham (U.S.)');
INSERT INTO external_library (address) VALUES ('Bismarck');
INSERT INTO external_library (address) VALUES ('Blanes');
INSERT INTO external_library (address) VALUES ('Bled');
INSERT INTO external_library (address) VALUES ('Blois');
INSERT INTO external_library (address) VALUES ('Blumenau');
INSERT INTO external_library (address) VALUES ('Boca Chica');
INSERT INTO external_library (address) VALUES ('Boca Raton');
INSERT INTO external_library (address) VALUES ('Bochum');
INSERT INTO external_library (address) VALUES ('Bodrum');
INSERT INTO external_library (address) VALUES ('Boise');
INSERT INTO external_library (address) VALUES ('Bologna');
INSERT INTO external_library (address) VALUES ('Bolzano');
INSERT INTO external_library (address) VALUES ('Bonifacio');
INSERT INTO external_library (address) VALUES ('Bonn');
INSERT INTO external_library (address) VALUES ('Bordeaux');
INSERT INTO external_library (address) VALUES ('Bormio');
INSERT INTO external_library (address) VALUES ('Boston');
INSERT INTO external_library (address) VALUES ('Boulder');
INSERT INTO external_library (address) VALUES ('Bourges');
INSERT INTO external_library (address) VALUES ('Boynton Beach');
INSERT INTO external_library (address) VALUES ('Bradenton');
INSERT INTO external_library (address) VALUES ('Bradford');
INSERT INTO external_library (address) VALUES ('Braga');
INSERT INTO external_library (address) VALUES ('Brampton');
INSERT INTO external_library (address) VALUES ('Brasilia');
INSERT INTO external_library (address) VALUES ('Braunschweig');
INSERT INTO external_library (address) VALUES ('Breda');
INSERT INTO external_library (address) VALUES ('Bregenz');
INSERT INTO external_library (address) VALUES ('Brela');
INSERT INTO external_library (address) VALUES ('Bremen');
INSERT INTO external_library (address) VALUES ('Bremerhaven');
INSERT INTO external_library (address) VALUES ('Brescia');
INSERT INTO external_library (address) VALUES ('Brest');
INSERT INTO external_library (address) VALUES ('Brighton');
INSERT INTO external_library (address) VALUES ('Brindisi');
INSERT INTO external_library (address) VALUES ('Brisbane');
INSERT INTO external_library (address) VALUES ('Bristol');
INSERT INTO external_library (address) VALUES ('Brixen');
INSERT INTO external_library (address) VALUES ('Brixental');
INSERT INTO external_library (address) VALUES ('Brno');
INSERT INTO external_library (address) VALUES ('Brownsville');
INSERT INTO external_library (address) VALUES ('Bruges');
INSERT INTO external_library (address) VALUES ('Brussels');
INSERT INTO external_library (address) VALUES ('Bucharest');
INSERT INTO external_library (address) VALUES ('Budva');
INSERT INTO external_library (address) VALUES ('Buenos Aires');
INSERT INTO external_library (address) VALUES ('Buffalo');
INSERT INTO external_library (address) VALUES ('Burgas');
INSERT INTO external_library (address) VALUES ('Cabo San Lucas');
INSERT INTO external_library (address) VALUES ('Cádiz');
INSERT INTO external_library (address) VALUES ('Caen');
INSERT INTO external_library (address) VALUES ('Cagliari');
INSERT INTO external_library (address) VALUES ('Cagnes-sur-Mer');
INSERT INTO external_library (address) VALUES ('Cairns');
INSERT INTO external_library (address) VALUES ('Cala Bona');
INSERT INTO external_library (address) VALUES ('Cala d´Or');
INSERT INTO external_library (address) VALUES ('Cala Millor');
INSERT INTO external_library (address) VALUES ('Cala Ratjada');
INSERT INTO external_library (address) VALUES ('Calais');
INSERT INTO external_library (address) VALUES ('Calella');
INSERT INTO external_library (address) VALUES ('Calgary');
INSERT INTO external_library (address) VALUES ('Caloundra');
INSERT INTO external_library (address) VALUES ('Calp');
INSERT INTO external_library (address) VALUES ('Caltanissetta');
INSERT INTO external_library (address) VALUES ('Calvi');
INSERT INTO external_library (address) VALUES ('Cambridge');
INSERT INTO external_library (address) VALUES ('Cambrils');
INSERT INTO external_library (address) VALUES ('Campinas');
INSERT INTO external_library (address) VALUES ('Campobasso');
INSERT INTO external_library (address) VALUES ('Can Picafort');
INSERT INTO external_library (address) VALUES ('Canazei');
INSERT INTO external_library (address) VALUES ('Canberra');
INSERT INTO external_library (address) VALUES ('Cancun');
INSERT INTO external_library (address) VALUES ('Cannes');
INSERT INTO external_library (address) VALUES ('Canterbury');
INSERT INTO external_library (address) VALUES ('Canyamel');
INSERT INTO external_library (address) VALUES ('Capdepera');
INSERT INTO external_library (address) VALUES ('Cape Canaveral');
INSERT INTO external_library (address) VALUES ('Cape Coral');
INSERT INTO external_library (address) VALUES ('Cape May');
INSERT INTO external_library (address) VALUES ('Cape Town');
INSERT INTO external_library (address) VALUES ('Carcassonne');
INSERT INTO external_library (address) VALUES ('Cardiff');
INSERT INTO external_library (address) VALUES ('Carlisle');
INSERT INTO external_library (address) VALUES ('Carlsbad');
INSERT INTO external_library (address) VALUES ('Carpi');
INSERT INTO external_library (address) VALUES ('Carpinteria');
INSERT INTO external_library (address) VALUES ('Carrara');
INSERT INTO external_library (address) VALUES ('Carson City');
INSERT INTO external_library (address) VALUES ('Cartagena');
INSERT INTO external_library (address) VALUES ('Casablanca');
INSERT INTO external_library (address) VALUES ('Caserta');
INSERT INTO external_library (address) VALUES ('Casper');
INSERT INTO external_library (address) VALUES ('Cassis');
INSERT INTO external_library (address) VALUES ('Castelrotto');
INSERT INTO external_library (address) VALUES ('Catania');
INSERT INTO external_library (address) VALUES ('Catanzaro');
INSERT INTO external_library (address) VALUES ('Caxias do Sul');
INSERT INTO external_library (address) VALUES ('Cervinia');
INSERT INTO external_library (address) VALUES ('Cesena');
INSERT INTO external_library (address) VALUES ('Český Krumlov');
INSERT INTO external_library (address) VALUES ('Çeşme');
INSERT INTO external_library (address) VALUES ('Chamonix');
INSERT INTO external_library (address) VALUES ('Chandler');
INSERT INTO external_library (address) VALUES ('Chania');
INSERT INTO external_library (address) VALUES ('Charleroi');
INSERT INTO external_library (address) VALUES ('Charleston (West Virginia)');
INSERT INTO external_library (address) VALUES ('Charleston (South Carolina)');
INSERT INTO external_library (address) VALUES ('Charlotte');
INSERT INTO external_library (address) VALUES ('Charlottetown');
INSERT INTO external_library (address) VALUES ('Chattanooga');
INSERT INTO external_library (address) VALUES ('Chelmsford');
INSERT INTO external_library (address) VALUES ('Chesapeake');
INSERT INTO external_library (address) VALUES ('Chester');
INSERT INTO external_library (address) VALUES ('Cheyenne');
INSERT INTO external_library (address) VALUES ('Chiang Mai');
INSERT INTO external_library (address) VALUES ('Chiang Rai');
INSERT INTO external_library (address) VALUES ('Chicago');
INSERT INTO external_library (address) VALUES ('Chieti');
INSERT INTO external_library (address) VALUES ('Chioggia');
INSERT INTO external_library (address) VALUES ('Chios');
INSERT INTO external_library (address) VALUES ('Chonburi');
INSERT INTO external_library (address) VALUES ('Christchurch');
INSERT INTO external_library (address) VALUES ('Chula Vista');
INSERT INTO external_library (address) VALUES ('Chur');
INSERT INTO external_library (address) VALUES ('Cincinnati');
INSERT INTO external_library (address) VALUES ('Ciutadella de Menorca');
INSERT INTO external_library (address) VALUES ('Civitavecchia');
INSERT INTO external_library (address) VALUES ('Clearwater');
INSERT INTO external_library (address) VALUES ('Clermont-Ferrand');
INSERT INTO external_library (address) VALUES ('Cleveland');
INSERT INTO external_library (address) VALUES ('Cocoa Beach');
INSERT INTO external_library (address) VALUES ('Coconut Creek');
INSERT INTO external_library (address) VALUES ('Coimbra');
INSERT INTO external_library (address) VALUES ('Collioure');
INSERT INTO external_library (address) VALUES ('Colmar');
INSERT INTO external_library (address) VALUES ('Cologne');
INSERT INTO external_library (address) VALUES ('Colorado Springs');
INSERT INTO external_library (address) VALUES ('Columbia');
INSERT INTO external_library (address) VALUES ('Columbus');
INSERT INTO external_library (address) VALUES ('Como');
INSERT INTO external_library (address) VALUES ('Concord');
INSERT INTO external_library (address) VALUES ('Conil de la Frontera');
INSERT INTO external_library (address) VALUES ('Copenhagen');
INSERT INTO external_library (address) VALUES ('Coral Springs');
INSERT INTO external_library (address) VALUES ('Córdoba (Argentina)');
INSERT INTO external_library (address) VALUES ('Córdoba (Spain)');
INSERT INTO external_library (address) VALUES ('Corfu');
INSERT INTO external_library (address) VALUES ('Corinth');
INSERT INTO external_library (address) VALUES ('Cork');
INSERT INTO external_library (address) VALUES ('Corpus Christi');
INSERT INTO external_library (address) VALUES ('Corralejo');
INSERT INTO external_library (address) VALUES ('Cortina d´Ampezzo');
INSERT INTO external_library (address) VALUES ('Cosenza');
INSERT INTO external_library (address) VALUES ('Costa Adeje');
INSERT INTO external_library (address) VALUES ('Courchevel');
INSERT INTO external_library (address) VALUES ('Courmayeur');
INSERT INTO external_library (address) VALUES ('Coventry');
INSERT INTO external_library (address) VALUES ('Cozumel');
INSERT INTO external_library (address) VALUES ('Crans-Montana');
INSERT INTO external_library (address) VALUES ('Cremona');
INSERT INTO external_library (address) VALUES ('Crotone');
INSERT INTO external_library (address) VALUES ('Cuneo');
INSERT INTO external_library (address) VALUES ('Da Nang');
INSERT INTO external_library (address) VALUES ('Dallas');
INSERT INTO external_library (address) VALUES ('Dana Point');
INSERT INTO external_library (address) VALUES ('Darmstadt');
INSERT INTO external_library (address) VALUES ('Darwin');
INSERT INTO external_library (address) VALUES ('Daugavpils');
INSERT INTO external_library (address) VALUES ('Davos');
INSERT INTO external_library (address) VALUES ('Daytona Beach');
INSERT INTO external_library (address) VALUES ('Deerfield Beach');
INSERT INTO external_library (address) VALUES ('Del Mar');
INSERT INTO external_library (address) VALUES ('Delft');
INSERT INTO external_library (address) VALUES ('Delray Beach');
INSERT INTO external_library (address) VALUES ('Denia');
INSERT INTO external_library (address) VALUES ('Denver');
INSERT INTO external_library (address) VALUES ('Derby');
INSERT INTO external_library (address) VALUES ('Derry');
INSERT INTO external_library (address) VALUES ('Des Moines');
INSERT INTO external_library (address) VALUES ('Detroit');
INSERT INTO external_library (address) VALUES ('Didim');
INSERT INTO external_library (address) VALUES ('Dieppe');
INSERT INTO external_library (address) VALUES ('Dijon');
INSERT INTO external_library (address) VALUES ('Doha');
INSERT INTO external_library (address) VALUES ('Dolomiti Superski');
INSERT INTO external_library (address) VALUES ('Dorfgastein');
INSERT INTO external_library (address) VALUES ('Dortmund');
INSERT INTO external_library (address) VALUES ('Dover');
INSERT INTO external_library (address) VALUES ('Dresden');
INSERT INTO external_library (address) VALUES ('Dubai');
INSERT INTO external_library (address) VALUES ('Dublin');
INSERT INTO external_library (address) VALUES ('Dubrovnik');
INSERT INTO external_library (address) VALUES ('Duisburg');
INSERT INTO external_library (address) VALUES ('Duluth');
INSERT INTO external_library (address) VALUES ('Dundalk');
INSERT INTO external_library (address) VALUES ('Dundee');
INSERT INTO external_library (address) VALUES ('Dunedin');
INSERT INTO external_library (address) VALUES ('Dunkirk');
INSERT INTO external_library (address) VALUES ('Durham');
INSERT INTO external_library (address) VALUES ('Durham');
INSERT INTO external_library (address) VALUES ('Düsseldorf');
INSERT INTO external_library (address) VALUES ('Eau Claire');
INSERT INTO external_library (address) VALUES ('Edinburgh');
INSERT INTO external_library (address) VALUES ('Edmonton');
INSERT INTO external_library (address) VALUES ('Eilat');
INSERT INTO external_library (address) VALUES ('Eindhoven');
INSERT INTO external_library (address) VALUES ('El Paso');
INSERT INTO external_library (address) VALUES ('Elche');
INSERT INTO external_library (address) VALUES ('Ellmau');
INSERT INTO external_library (address) VALUES ('Elm');
INSERT INTO external_library (address) VALUES ('Empuriabrava');
INSERT INTO external_library (address) VALUES ('Encinitas');
INSERT INTO external_library (address) VALUES ('Engelberg');
INSERT INTO external_library (address) VALUES ('Enna');
INSERT INTO external_library (address) VALUES ('Enschede');
INSERT INTO external_library (address) VALUES ('Erfurt');
INSERT INTO external_library (address) VALUES ('Erie');
INSERT INTO external_library (address) VALUES ('Erlangen');
INSERT INTO external_library (address) VALUES ('Esbjerg');
INSERT INTO external_library (address) VALUES ('Espace Killy');
INSERT INTO external_library (address) VALUES ('Essaouira');
INSERT INTO external_library (address) VALUES ('Essen');
INSERT INTO external_library (address) VALUES ('Estepona');
INSERT INTO external_library (address) VALUES ('Eugene');
INSERT INTO external_library (address) VALUES ('Exeter');
INSERT INTO external_library (address) VALUES ('Faenza');
INSERT INTO external_library (address) VALUES ('Falmouth');
INSERT INTO external_library (address) VALUES ('Famagusta');
INSERT INTO external_library (address) VALUES ('Fano');
INSERT INTO external_library (address) VALUES ('Fargo');
INSERT INTO external_library (address) VALUES ('Faro');
INSERT INTO external_library (address) VALUES ('Fayetteville');
INSERT INTO external_library (address) VALUES ('Fermo');
INSERT INTO external_library (address) VALUES ('Fernandina Beach');
INSERT INTO external_library (address) VALUES ('Ferrara');
INSERT INTO external_library (address) VALUES ('Fethiye');
INSERT INTO external_library (address) VALUES ('Fez');
INSERT INTO external_library (address) VALUES ('Fieberbrunn');
INSERT INTO external_library (address) VALUES ('Filzmoos');
INSERT INTO external_library (address) VALUES ('Fiumicino');
INSERT INTO external_library (address) VALUES ('Flagstaff');
INSERT INTO external_library (address) VALUES ('Flaine');
INSERT INTO external_library (address) VALUES ('Florence');
INSERT INTO external_library (address) VALUES ('Foggia');
INSERT INTO external_library (address) VALUES ('Folgarida');
INSERT INTO external_library (address) VALUES ('Fontana');
INSERT INTO external_library (address) VALUES ('Forlì');
INSERT INTO external_library (address) VALUES ('Fort Collins');
INSERT INTO external_library (address) VALUES ('Fort Lauderdale');
INSERT INTO external_library (address) VALUES ('Fort Myers');
INSERT INTO external_library (address) VALUES ('Fort Wayne');
INSERT INTO external_library (address) VALUES ('Fort Worth');
INSERT INTO external_library (address) VALUES ('Forte dei Marmi');
INSERT INTO external_library (address) VALUES ('Foz do Iguaçu');
INSERT INTO external_library (address) VALUES ('Frankfort');
INSERT INTO external_library (address) VALUES ('Frankfurt am Main');
INSERT INTO external_library (address) VALUES ('Fredericton');
INSERT INTO external_library (address) VALUES ('Freeport');
INSERT INTO external_library (address) VALUES ('Freiburg');
INSERT INTO external_library (address) VALUES ('Fremont');
INSERT INTO external_library (address) VALUES ('Fresno');
INSERT INTO external_library (address) VALUES ('Fribourg');
INSERT INTO external_library (address) VALUES ('Frosinone');
INSERT INTO external_library (address) VALUES ('Fuengirola');
INSERT INTO external_library (address) VALUES ('Fujairah');
INSERT INTO external_library (address) VALUES ('Fukuoka');
INSERT INTO external_library (address) VALUES ('Funchal');
INSERT INTO external_library (address) VALUES ('Gainesville');
INSERT INTO external_library (address) VALUES ('Galtür');
INSERT INTO external_library (address) VALUES ('Galway');
INSERT INTO external_library (address) VALUES ('Garden Grove');
INSERT INTO external_library (address) VALUES ('Garland');
INSERT INTO external_library (address) VALUES ('Gatineau');
INSERT INTO external_library (address) VALUES ('Geelong');
INSERT INTO external_library (address) VALUES ('Geneva');
INSERT INTO external_library (address) VALUES ('Genoa');
INSERT INTO external_library (address) VALUES ('George Town');
INSERT INTO external_library (address) VALUES ('Ghent');
INSERT INTO external_library (address) VALUES ('Gijón');
INSERT INTO external_library (address) VALUES ('Gilbert');
INSERT INTO external_library (address) VALUES ('Girona');
INSERT INTO external_library (address) VALUES ('Glasgow');
INSERT INTO external_library (address) VALUES ('Glendale (Arizona)');
INSERT INTO external_library (address) VALUES ('Glendale (California)');
INSERT INTO external_library (address) VALUES ('Gloucester');
INSERT INTO external_library (address) VALUES ('Gold Coast');
INSERT INTO external_library (address) VALUES ('Gorizia');
INSERT INTO external_library (address) VALUES ('Dachstein-West');
INSERT INTO external_library (address) VALUES ('Gothenburg');
INSERT INTO external_library (address) VALUES ('Granada');
INSERT INTO external_library (address) VALUES ('Grand Prairie');
INSERT INTO external_library (address) VALUES ('Grand Rapids');
INSERT INTO external_library (address) VALUES ('Grasse');
INSERT INTO external_library (address) VALUES ('Great Falls');
INSERT INTO external_library (address) VALUES ('Green Bay');
INSERT INTO external_library (address) VALUES ('Greensboro');
INSERT INTO external_library (address) VALUES ('Grenoble');
INSERT INTO external_library (address) VALUES ('Grindelwald');
INSERT INTO external_library (address) VALUES ('Groningen');
INSERT INTO external_library (address) VALUES ('Grossarl');
INSERT INTO external_library (address) VALUES ('Grosseto');
INSERT INTO external_library (address) VALUES ('Gstaad');
INSERT INTO external_library (address) VALUES ('Guadalajara');
INSERT INTO external_library (address) VALUES ('Guangzhou');
INSERT INTO external_library (address) VALUES ('Guimarães');
INSERT INTO external_library (address) VALUES ('Haarlem');
INSERT INTO external_library (address) VALUES ('Haifa');
INSERT INTO external_library (address) VALUES ('Halifax');
INSERT INTO external_library (address) VALUES ('Hamburg');
INSERT INTO external_library (address) VALUES ('Hamilton (Canada)');
INSERT INTO external_library (address) VALUES ('Hamilton (New Zealand)');
INSERT INTO external_library (address) VALUES ('Hampton');
INSERT INTO external_library (address) VALUES ('Hangzhou');
INSERT INTO external_library (address) VALUES ('Hannover');
INSERT INTO external_library (address) VALUES ('Hanoi');
INSERT INTO external_library (address) VALUES ('Harrisburg');
INSERT INTO external_library (address) VALUES ('Hartford');
INSERT INTO external_library (address) VALUES ('Hasselt');
INSERT INTO external_library (address) VALUES ('Hat Yai');
INSERT INTO external_library (address) VALUES ('Havana');
INSERT INTO external_library (address) VALUES ('Heidelberg');
INSERT INTO external_library (address) VALUES ('Heiligenblut');
INSERT INTO external_library (address) VALUES ('Helena');
INSERT INTO external_library (address) VALUES ('Helsinki');
INSERT INTO external_library (address) VALUES ('Henderson');
INSERT INTO external_library (address) VALUES ('Heraklion');
INSERT INTO external_library (address) VALUES ('Herceg Novi');
INSERT INTO external_library (address) VALUES ('Hereford');
INSERT INTO external_library (address) VALUES ('Hermosa Beach');
INSERT INTO external_library (address) VALUES ('Hervey Bay');
INSERT INTO external_library (address) VALUES ('Hialeah');
INSERT INTO external_library (address) VALUES ('Hinterglemm');
INSERT INTO external_library (address) VALUES ('Hinterstoder');
INSERT INTO external_library (address) VALUES ('Hiroshima');
INSERT INTO external_library (address) VALUES ('Hoi An');
INSERT INTO external_library (address) VALUES ('Hobart');
INSERT INTO external_library (address) VALUES ('Ho Chi Minh City');
INSERT INTO external_library (address) VALUES ('Hollywood (Florida)');
INSERT INTO external_library (address) VALUES ('Hong Kong');
INSERT INTO external_library (address) VALUES ('Honolulu');
INSERT INTO external_library (address) VALUES ('Horsens');
INSERT INTO external_library (address) VALUES ('Houston');
INSERT INTO external_library (address) VALUES ('Hua Hin');
INSERT INTO external_library (address) VALUES ('Hue');
INSERT INTO external_library (address) VALUES ('Huntington Beach');
INSERT INTO external_library (address) VALUES ('Huntsville');
INSERT INTO external_library (address) VALUES ('Hvar');
INSERT INTO external_library (address) VALUES ('Hyères');
INSERT INTO external_library (address) VALUES ('Ibiza Town');
INSERT INTO external_library (address) VALUES ('Imola');
INSERT INTO external_library (address) VALUES ('Imperia');
INSERT INTO external_library (address) VALUES ('Inca');
INSERT INTO external_library (address) VALUES ('Indianapolis');
INSERT INTO external_library (address) VALUES ('Ingolstadt');
INSERT INTO external_library (address) VALUES ('Innsbruck');
INSERT INTO external_library (address) VALUES ('Interlaken');
INSERT INTO external_library (address) VALUES ('Inverness');
INSERT INTO external_library (address) VALUES ('Ioannina');
INSERT INTO external_library (address) VALUES ('Irvine');
INSERT INTO external_library (address) VALUES ('Irving');
INSERT INTO external_library (address) VALUES ('Ischgl');
INSERT INTO external_library (address) VALUES ('Isernia');
INSERT INTO external_library (address) VALUES ('Islamorada');
INSERT INTO external_library (address) VALUES ('Istanbul');
INSERT INTO external_library (address) VALUES ('İzmir');
INSERT INTO external_library (address) VALUES ('Izola');
INSERT INTO external_library (address) VALUES ('Jackson');
INSERT INTO external_library (address) VALUES ('Jacksonville');
INSERT INTO external_library (address) VALUES ('Jefferson City');
INSERT INTO external_library (address) VALUES ('Jena');
INSERT INTO external_library (address) VALUES ('Jerez de la Frontera');
INSERT INTO external_library (address) VALUES ('Jersey City');
INSERT INTO external_library (address) VALUES ('Jerusalem');
INSERT INTO external_library (address) VALUES ('Johannesburg');
INSERT INTO external_library (address) VALUES ('Joinville');
INSERT INTO external_library (address) VALUES ('Juan-les-Pins');
INSERT INTO external_library (address) VALUES ('Juiz de Fora');
INSERT INTO external_library (address) VALUES ('Juneau');
INSERT INTO external_library (address) VALUES ('Jungfrau');
INSERT INTO external_library (address) VALUES ('Jupiter');
INSERT INTO external_library (address) VALUES ('Jūrmala');
INSERT INTO external_library (address) VALUES ('Kalamata');
INSERT INTO external_library (address) VALUES ('Kanchanaburi');
INSERT INTO external_library (address) VALUES ('Kansas City');
INSERT INTO external_library (address) VALUES ('Kansas City (Kansas)');
INSERT INTO external_library (address) VALUES ('Kappl');
INSERT INTO external_library (address) VALUES ('Kaprun');
INSERT INTO external_library (address) VALUES ('Karlovy Vary');
INSERT INTO external_library (address) VALUES ('Karlsruhe');
INSERT INTO external_library (address) VALUES ('Kassel');
INSERT INTO external_library (address) VALUES ('Kastoria');
INSERT INTO external_library (address) VALUES ('Kaunas');
INSERT INTO external_library (address) VALUES ('Kavala');
INSERT INTO external_library (address) VALUES ('Kemer');
INSERT INTO external_library (address) VALUES ('Key Largo');
INSERT INTO external_library (address) VALUES ('Key West');
INSERT INTO external_library (address) VALUES ('Khao Lak');
INSERT INTO external_library (address) VALUES ('Kiel');
INSERT INTO external_library (address) VALUES ('Kilkenny');
INSERT INTO external_library (address) VALUES ('Kingston');
INSERT INTO external_library (address) VALUES ('Kingston upon Hull');
INSERT INTO external_library (address) VALUES ('Kissimmee');
INSERT INTO external_library (address) VALUES ('Kitzbühel');
INSERT INTO external_library (address) VALUES ('Klagenfurt');
INSERT INTO external_library (address) VALUES ('Klaipėda');
INSERT INTO external_library (address) VALUES ('Knoxville');
INSERT INTO external_library (address) VALUES ('Kobe');
INSERT INTO external_library (address) VALUES ('Koblenz');
INSERT INTO external_library (address) VALUES ('Kolding');
INSERT INTO external_library (address) VALUES ('Komotini');
INSERT INTO external_library (address) VALUES ('Koper');
INSERT INTO external_library (address) VALUES ('Kos');
INSERT INTO external_library (address) VALUES ('Košice');
INSERT INTO external_library (address) VALUES ('Kotor');
INSERT INTO external_library (address) VALUES ('Krabi');
INSERT INTO external_library (address) VALUES ('Krakow');
INSERT INTO external_library (address) VALUES ('Kuah');
INSERT INTO external_library (address) VALUES ('Kuala Lumpur');
INSERT INTO external_library (address) VALUES ('Kuşadası');
INSERT INTO external_library (address) VALUES ('Kutná Hora');
INSERT INTO external_library (address) VALUES ('Kyoto');
INSERT INTO external_library (address) VALUES ('Kyrenia');
INSERT INTO external_library (address) VALUES ('La Ciotat');
INSERT INTO external_library (address) VALUES ('La Clusaz');
INSERT INTO external_library (address) VALUES ('La Laguna');
INSERT INTO external_library (address) VALUES ('La Maddalena');
INSERT INTO external_library (address) VALUES ('La Manga');
INSERT INTO external_library (address) VALUES ('La Plagne');
INSERT INTO external_library (address) VALUES ('La Plata');
INSERT INTO external_library (address) VALUES ('La Rochelle');
INSERT INTO external_library (address) VALUES ('La Romana');
INSERT INTO external_library (address) VALUES ('La Spezia');
INSERT INTO external_library (address) VALUES ('La Thuile');
INSERT INTO external_library (address) VALUES ('Laax');
INSERT INTO external_library (address) VALUES ('Lagos');
INSERT INTO external_library (address) VALUES ('Laguna Beach');
INSERT INTO external_library (address) VALUES ('Lakeland');
INSERT INTO external_library (address) VALUES ('Lamezia Terme');
INSERT INTO external_library (address) VALUES ('Lancaster');
INSERT INTO external_library (address) VALUES ('Lancaster (U.S.)');
INSERT INTO external_library (address) VALUES ('Lansing');
INSERT INTO external_library (address) VALUES ('L´Aquila');
INSERT INTO external_library (address) VALUES ('Laredo');
INSERT INTO external_library (address) VALUES ('Largo');
INSERT INTO external_library (address) VALUES ('Larnaca');
INSERT INTO external_library (address) VALUES ('Las Palmas');
INSERT INTO external_library (address) VALUES ('Las Vegas');
INSERT INTO external_library (address) VALUES ('Latina');
INSERT INTO external_library (address) VALUES ('Lausanne');
INSERT INTO external_library (address) VALUES ('Laval');
INSERT INTO external_library (address) VALUES ('Le Havre');
INSERT INTO external_library (address) VALUES ('Le Lavandou');
INSERT INTO external_library (address) VALUES ('Lecce');
INSERT INTO external_library (address) VALUES ('Lecco');
INSERT INTO external_library (address) VALUES ('Lech');
INSERT INTO external_library (address) VALUES ('Leeds');
INSERT INTO external_library (address) VALUES ('Legnano');
INSERT INTO external_library (address) VALUES ('Leicester');
INSERT INTO external_library (address) VALUES ('Leiden');
INSERT INTO external_library (address) VALUES ('Leipzig');
INSERT INTO external_library (address) VALUES ('Leogang');
INSERT INTO external_library (address) VALUES ('Les Arcs');
INSERT INTO external_library (address) VALUES ('Les Deux Alpes');
INSERT INTO external_library (address) VALUES ('Les Gets');
INSERT INTO external_library (address) VALUES ('Les Houches');
INSERT INTO external_library (address) VALUES ('Les Menuires');
INSERT INTO external_library (address) VALUES ('Leuven');
INSERT INTO external_library (address) VALUES ('Lexington');
INSERT INTO external_library (address) VALUES ('Liberec');
INSERT INTO external_library (address) VALUES ('Liège');
INSERT INTO external_library (address) VALUES ('Lienz');
INSERT INTO external_library (address) VALUES ('Liepāja');
INSERT INTO external_library (address) VALUES ('Lille');
INSERT INTO external_library (address) VALUES ('Limassol');
INSERT INTO external_library (address) VALUES ('Limerick');
INSERT INTO external_library (address) VALUES ('Limoges');
INSERT INTO external_library (address) VALUES ('Lincoln');
INSERT INTO external_library (address) VALUES ('Lincoln');
INSERT INTO external_library (address) VALUES ('Lindos');
INSERT INTO external_library (address) VALUES ('Linz');
INSERT INTO external_library (address) VALUES ('Lisbon');
INSERT INTO external_library (address) VALUES ('Lisburn');
INSERT INTO external_library (address) VALUES ('Little Rock');
INSERT INTO external_library (address) VALUES ('Liverpool');
INSERT INTO external_library (address) VALUES ('Livigno');
INSERT INTO external_library (address) VALUES ('Livorno');
INSERT INTO external_library (address) VALUES ('Ljubljana');
INSERT INTO external_library (address) VALUES ('Lloret de Mar');
INSERT INTO external_library (address) VALUES ('Locarno');
INSERT INTO external_library (address) VALUES ('London (Canada)');
INSERT INTO external_library (address) VALUES ('London (UK)');
INSERT INTO external_library (address) VALUES ('Londrina');
INSERT INTO external_library (address) VALUES ('Long Beach');
INSERT INTO external_library (address) VALUES ('Los Angeles');
INSERT INTO external_library (address) VALUES ('Los Cabos');
INSERT INTO external_library (address) VALUES ('Los Cristianos');
INSERT INTO external_library (address) VALUES ('Louisville');
INSERT INTO external_library (address) VALUES ('Loutraki');
INSERT INTO external_library (address) VALUES ('Louvain-la-Neuve');
INSERT INTO external_library (address) VALUES ('Lubbock');
INSERT INTO external_library (address) VALUES ('Lübeck');
INSERT INTO external_library (address) VALUES ('Lucca');
INSERT INTO external_library (address) VALUES ('Lucerne');
INSERT INTO external_library (address) VALUES ('Lugano');
INSERT INTO external_library (address) VALUES ('Lund');
INSERT INTO external_library (address) VALUES ('Lyon');
INSERT INTO external_library (address) VALUES ('Maastricht');
INSERT INTO external_library (address) VALUES ('Madison');
INSERT INTO external_library (address) VALUES ('Madonna di Campiglio');
INSERT INTO external_library (address) VALUES ('Madrid');
INSERT INTO external_library (address) VALUES ('Magaluf');
INSERT INTO external_library (address) VALUES ('Mahón');
INSERT INTO external_library (address) VALUES ('Mainz');
INSERT INTO external_library (address) VALUES ('Makarska');
INSERT INTO external_library (address) VALUES ('Malaga');
INSERT INTO external_library (address) VALUES ('Malia');
INSERT INTO external_library (address) VALUES ('Malibu');
INSERT INTO external_library (address) VALUES ('Malmö');
INSERT INTO external_library (address) VALUES ('Manacor');
INSERT INTO external_library (address) VALUES ('Manchester');
INSERT INTO external_library (address) VALUES ('Manhattan Beach');
INSERT INTO external_library (address) VALUES ('Mannheim');
INSERT INTO external_library (address) VALUES ('Manosque');
INSERT INTO external_library (address) VALUES ('Mar del Plata');
INSERT INTO external_library (address) VALUES ('Marathon');
INSERT INTO external_library (address) VALUES ('Marbella');
INSERT INTO external_library (address) VALUES ('Maria Alm');
INSERT INTO external_library (address) VALUES ('Maribor');
INSERT INTO external_library (address) VALUES ('Markham');
INSERT INTO external_library (address) VALUES ('Marmaris');
INSERT INTO external_library (address) VALUES ('Maroochydore');
INSERT INTO external_library (address) VALUES ('Marrakesh');
INSERT INTO external_library (address) VALUES ('Marsala');
INSERT INTO external_library (address) VALUES ('Marseille');
INSERT INTO external_library (address) VALUES ('Maspalomas');
INSERT INTO external_library (address) VALUES ('Matera');
INSERT INTO external_library (address) VALUES ('Mayrhofen');
INSERT INTO external_library (address) VALUES ('Mazara del Vallo');
INSERT INTO external_library (address) VALUES ('Mechelen');
INSERT INTO external_library (address) VALUES ('Melbourne (Australia)');
INSERT INTO external_library (address) VALUES ('Melbourne (U.S.)');
INSERT INTO external_library (address) VALUES ('Memphis');
INSERT INTO external_library (address) VALUES ('Menton');
INSERT INTO external_library (address) VALUES ('Merano');
INSERT INTO external_library (address) VALUES ('Meribel');
INSERT INTO external_library (address) VALUES ('Mérida');
INSERT INTO external_library (address) VALUES ('Mesa');
INSERT INTO external_library (address) VALUES ('Messina');
INSERT INTO external_library (address) VALUES ('Mestre');
INSERT INTO external_library (address) VALUES ('Metz');
INSERT INTO external_library (address) VALUES ('Mexico City');
INSERT INTO external_library (address) VALUES ('Miami');
INSERT INTO external_library (address) VALUES ('Middelburg');
INSERT INTO external_library (address) VALUES ('Midland');
INSERT INTO external_library (address) VALUES ('Mijas');
INSERT INTO external_library (address) VALUES ('Milan');
INSERT INTO external_library (address) VALUES ('Millau');
INSERT INTO external_library (address) VALUES ('Milwaukee');
INSERT INTO external_library (address) VALUES ('Minneapolis');
INSERT INTO external_library (address) VALUES ('Miramar');
INSERT INTO external_library (address) VALUES ('Mississauga');
INSERT INTO external_library (address) VALUES ('Moab');
INSERT INTO external_library (address) VALUES ('Mobile');
INSERT INTO external_library (address) VALUES ('Modena');
INSERT INTO external_library (address) VALUES ('Modesto');
INSERT INTO external_library (address) VALUES ('Modica');
INSERT INTO external_library (address) VALUES ('Moena');
INSERT INTO external_library (address) VALUES ('Mogi das Cruzes');
INSERT INTO external_library (address) VALUES ('Mons');
INSERT INTO external_library (address) VALUES ('Monte Rosa');
INSERT INTO external_library (address) VALUES ('Montego Bay');
INSERT INTO external_library (address) VALUES ('Montepulciano');
INSERT INTO external_library (address) VALUES ('Monterey');
INSERT INTO external_library (address) VALUES ('Montgomery');
INSERT INTO external_library (address) VALUES ('Montpelier');
INSERT INTO external_library (address) VALUES ('Montpellier');
INSERT INTO external_library (address) VALUES ('Montreal');
INSERT INTO external_library (address) VALUES ('Montreux');
INSERT INTO external_library (address) VALUES ('Monza');
INSERT INTO external_library (address) VALUES ('Moraira');
INSERT INTO external_library (address) VALUES ('Moreno Valley');
INSERT INTO external_library (address) VALUES ('Morzine');
INSERT INTO external_library (address) VALUES ('Mountain View');
INSERT INTO external_library (address) VALUES ('Mulhouse');
INSERT INTO external_library (address) VALUES ('Munich');
INSERT INTO external_library (address) VALUES ('Münster');
INSERT INTO external_library (address) VALUES ('Murcia');
INSERT INTO external_library (address) VALUES ('Murter');
INSERT INTO external_library (address) VALUES ('Mykonos');
INSERT INTO external_library (address) VALUES ('Mytilene');
INSERT INTO external_library (address) VALUES ('Nafplio');
INSERT INTO external_library (address) VALUES ('Nagoya');
INSERT INTO external_library (address) VALUES ('Namur');
INSERT INTO external_library (address) VALUES ('Nancy');
INSERT INTO external_library (address) VALUES ('Nantes');
INSERT INTO external_library (address) VALUES ('Napa');
INSERT INTO external_library (address) VALUES ('Naples (Italy)');
INSERT INTO external_library (address) VALUES ('Naples (U.S.)');
INSERT INTO external_library (address) VALUES ('Narbonne');
INSERT INTO external_library (address) VALUES ('Narva');
INSERT INTO external_library (address) VALUES ('Nashville');
INSERT INTO external_library (address) VALUES ('Nassau');
INSERT INTO external_library (address) VALUES ('Naxos');
INSERT INTO external_library (address) VALUES ('Nazareth');
INSERT INTO external_library (address) VALUES ('Negril');
INSERT INTO external_library (address) VALUES ('Nelson');
INSERT INTO external_library (address) VALUES ('Nerja');
INSERT INTO external_library (address) VALUES ('Netanya');
INSERT INTO external_library (address) VALUES ('Nevers');
INSERT INTO external_library (address) VALUES ('New Haven');
INSERT INTO external_library (address) VALUES ('New Orleans');
INSERT INTO external_library (address) VALUES ('New Smyrna Beach');
INSERT INTO external_library (address) VALUES ('New York City');
INSERT INTO external_library (address) VALUES ('Newark');
INSERT INTO external_library (address) VALUES ('Newcastle (Australia)');
INSERT INTO external_library (address) VALUES ('Newcastle (UK)');
INSERT INTO external_library (address) VALUES ('Newport');
INSERT INTO external_library (address) VALUES ('Newport Beach');
INSERT INTO external_library (address) VALUES ('Newport News');
INSERT INTO external_library (address) VALUES ('Nha Trang');
INSERT INTO external_library (address) VALUES ('Niagara Falls');
INSERT INTO external_library (address) VALUES ('Nice');
INSERT INTO external_library (address) VALUES ('Nicosia');
INSERT INTO external_library (address) VALUES ('Nijmegen');
INSERT INTO external_library (address) VALUES ('Nimes');
INSERT INTO external_library (address) VALUES ('Niort');
INSERT INTO external_library (address) VALUES ('Noosa Heads');
INSERT INTO external_library (address) VALUES ('Norfolk');
INSERT INTO external_library (address) VALUES ('North Las Vegas');
INSERT INTO external_library (address) VALUES ('North Port');
INSERT INTO external_library (address) VALUES ('Norwich');
INSERT INTO external_library (address) VALUES ('Nottingham');
INSERT INTO external_library (address) VALUES ('Novara');
INSERT INTO external_library (address) VALUES ('Novigrad');
INSERT INTO external_library (address) VALUES ('Nürnberg');
INSERT INTO external_library (address) VALUES ('Nyon');
INSERT INTO external_library (address) VALUES ('Oakland');
INSERT INTO external_library (address) VALUES ('Oaxaca');
INSERT INTO external_library (address) VALUES ('Obergurgl');
INSERT INTO external_library (address) VALUES ('Ocala');
INSERT INTO external_library (address) VALUES ('Oceanside');
INSERT INTO external_library (address) VALUES ('Ocho Rios');
INSERT INTO external_library (address) VALUES ('Odense');
INSERT INTO external_library (address) VALUES ('Odessa');
INSERT INTO external_library (address) VALUES ('Ogden');
INSERT INTO external_library (address) VALUES ('Oia');
INSERT INTO external_library (address) VALUES ('Oklahoma City');
INSERT INTO external_library (address) VALUES ('Olbia');
INSERT INTO external_library (address) VALUES ('Olomouc');
INSERT INTO external_library (address) VALUES ('Olympia');
INSERT INTO external_library (address) VALUES ('Omaha');
INSERT INTO external_library (address) VALUES ('Opatija');
INSERT INTO external_library (address) VALUES ('Orlando');
INSERT INTO external_library (address) VALUES ('Orléans');
INSERT INTO external_library (address) VALUES ('Ortisei');
INSERT INTO external_library (address) VALUES ('Osaka');
INSERT INTO external_library (address) VALUES ('Oslo');
INSERT INTO external_library (address) VALUES ('Ostrava');
INSERT INTO external_library (address) VALUES ('Ottawa');
INSERT INTO external_library (address) VALUES ('Oulu');
INSERT INTO external_library (address) VALUES ('Overland Park');
INSERT INTO external_library (address) VALUES ('Oviedo');
INSERT INTO external_library (address) VALUES ('Oxford');
INSERT INTO external_library (address) VALUES ('Oxnard');
INSERT INTO external_library (address) VALUES ('Padova');
INSERT INTO external_library (address) VALUES ('Palanga');
INSERT INTO external_library (address) VALUES ('Palavas-les-Flots');
INSERT INTO external_library (address) VALUES ('Palermo');

--===================================================================================================================
--version 0.4.6
DROP TABLE IF EXISTS books_in_internal_libraries;
DROP TABLE IF EXISTS books_in_external_libraries;

CREATE TABLE books_in_internal_libraries (
    library_id bigint NOT NULL,
    book_id bigint NOT NULL,

    FOREIGN KEY (library_id) REFERENCES library(id),
    FOREIGN KEY (book_id) REFERENCES book(id)
);

CREATE TABLE books_in_external_libraries (
    library_id bigint NOT NULL,
    book_id bigint NOT NULL,

    FOREIGN KEY (library_id) REFERENCES external_library(id),
    FOREIGN KEY (book_id) REFERENCES book(id)
);

INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2001);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2001);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2001);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3004, 2001);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2001);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2002);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2002);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2002);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3004, 2002);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2002);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2004);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2005);

INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3013, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3014, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3025, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3027, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3031, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3032, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3043, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3044, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3045, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3057, 2002);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3013, 2003);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3014, 2003);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3025, 2003);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3027, 2003);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3031, 2003);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3032, 2005);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3043, 2005);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3044, 2005);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3045, 2005);
INSERT INTO books_in_external_libraries (library_id, book_id) VALUES (3057, 2005);


--===================================================================================================================
--version 0.4.7
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3004, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2003);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2005);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3004, 2005);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2007);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2007);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2005);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2008);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2013);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2013);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3004, 2013);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2013);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2013);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2013);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3004, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3001, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3002, 2015);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2012);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2011);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2010);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2009);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2016);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2017);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2018);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2019);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3005, 2020);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2021);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2022);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2023);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2024);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2025);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2002);
INSERT INTO books_in_internal_libraries (library_id, book_id) VALUES (3003, 2010);
